[build]
  publish = "."

[[redirects]]
  from = "/page/*"
  to = "/page.html"
  status = 200

[[redirects]]
  from = "/work/*"
  to = "/work.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
